# Generated by Django 2.2.3 on 2019-07-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='abc@gmail.com', max_length=1000)),
                ('customer_name', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('file', models.FileField(null=True, upload_to='attachments/')),
                ('deliver_address', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(default='', max_length=100)),
                ('product_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=100)),
                ('size', models.CharField(choices=[('L', 'L'), ('S', 'S'), ('M', 'M'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=100)),
                ('price', models.IntegerField(default=10)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specs.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='', max_length=100)),
                ('shipping_address', models.CharField(default='', max_length=100)),
                ('pin_code', models.IntegerField()),
                ('state', models.CharField(default='Maharastra', max_length=100)),
                ('city', models.CharField(default='Pune', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('carts', models.ManyToManyField(to='specs.Products')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='', max_length=100)),
                ('deliver_address', models.CharField(default='', max_length=1000)),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='specs.Industry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specs.Products')),
            ],
        ),
    ]
