# Generated by Django 2.2.3 on 2019-07-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='city',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='state',
        ),
    ]
