# Generated by Django 2.2.3 on 2019-07-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_auto_20190713_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
